services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_SERVER_HOST: localhost:5000
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        DATABASE_PACKAGES: pg pg-hstore
    environment:
      CORS_ORIGIN: http://localhost:3000
      STATIC_DIRECTORY: ./public
      DATABASE_URL: postgres://postgres:sergtsop@database:5432/todos
    volumes:
      - ./backend/src:/app/src
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sergtsop
      POSTGRES_DB: todos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
